import React from "react";
import { Geist, Geist_Mono, Roboto_Flex, Roboto } from "next/font/google";
import "./globals.css";
import CartWrapper from './utils/cartWrapper';
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { AuthProvider } from "./auth/authContext";
import '../app/styles/omoss.css';

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const robotoFlex = Roboto_Flex({ weight: ['400', '700'], subsets: ['latin'] });
const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} ${robotoFlex.variable} ${roboto.variable} antialiased`}>
        <AuthProvider>
          <CartWrapper>
            <Navbar />
            {/* Main content grows to fill available space */}
            <main className="flex-grow">{children}</main>
            {/* Footer stays at the bottom */}
            <Footer />
          </CartWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
