import React from "react";
import { Geist, Geist_Mono, Roboto_Flex, Roboto } from "next/font/google";

import "../globals.css";


import CartWrapper from "../utils/cartWrapper";

import Footer from "../components/Footer";

import { AuthProvider } from "../auth/authContext";

import "../../src/app/globals.css"; // Ensure global styles are applied

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const robotoFlex = Roboto_Flex({ weight: ['400', '700'], subsets: ['latin'] });
const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} ${robotoFlex.variable} ${roboto.variable} antialiased`}>
        <AuthProvider>
          {/* Navbar always at top */}
          <Navbar />

          {/* Main content grows to fill remaining space */}
          <CartWrapper>
            <main className="flex-grow">{children}</main>
          </CartWrapper>

          {/* Footer always at bottom */}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
